### ISSUE TITLE
[bug?] api match 

### ISSUE THREAD

**Issue by yolio2003** [farrow-js/farrow#130]
![image](https://user-images.githubusercontent.com/352931/142748336-2da0591d-39e4-422b-b3b5-09c0afab4f3f.png)

as shown in the capture, if the order is reserved, `/api/cardlist` and `/api/cardtag` will always only match `/api/card`

is this a bug? or how to match excatly?

**Comment by Lucifier129** [comment]
Sorry, I didn't get it.

Following the code you have shown above, each route is different, matching idenpendently. What's happening?

**Comment by yolio2003** [comment]
when the `/api/card` is before `/api/cardlist` , the codegen only compled `/api/card` to `/api/cardlist`
I encountered a problem when I tried it on the weekend. The compiled front-end api code was expected to be `/api/cardlist`. As a result, because the order of `/api/card` was in front, the generated code was actually `/api/card`.

But this order problem does not seem to be an real bug, so what I want to ask is, is there an inaccurate match by default?

**Comment by Lucifier129** [comment]
The `codegen` in `farrow` is for `farrow-api`, not for `farrow-http`'s routes.

So each service in its own route has individual codegen/file, and they should be configured in `farrow.config.js` independently

**Comment by yolio2003** [comment]
i'm sure the config is correct, so this must be some bug?
![image](https://user-images.githubusercontent.com/352931/143001086-d520f289-8baf-4adc-a3ce-7a45e74b7a26.png)
![image](https://user-images.githubusercontent.com/352931/143001124-3d92a597-b5df-42a9-be55-3de175f8f9c2.png)
![image](https://user-images.githubusercontent.com/352931/143001183-ae3163af-1721-4212-904f-213c27b28d43.png)
if i change the route, the code gen result is difference.

**Comment by Lucifier129** [comment]
Oh, it's strange. Can you show the `api` configuration in `farrow.config.js`?

**Comment by Lucifier129** [comment]
Maybe the `introspection request` was passed in the wrong way, we will check it later, thx.

**Comment by tqma113** [comment]
https://github.com/farrow-js/farrow/blob/e7f9a215dc0e0936f0cb34498d04b266cfa5ecad/packages/farrow-http/src/basenames.ts#L24
I get the reason. Fix work in progress.

**Comment by tqma113** [comment]
https://www.npmjs.com/package/farrow-http/v/1.10.11
