### ISSUE TITLE
[bug] did not change any but http.serve just not woking in windows now

### ISSUE THREAD

**Issue by yolio2003** [farrow-js/farrow#135]
it works well before, but today

![image](https://user-images.githubusercontent.com/352931/143675526-4dfdbffa-7c6d-4a6e-b373-493f1e568133.png)
![image](https://user-images.githubusercontent.com/352931/143675578-ef815a10-d0f7-4756-805f-9eb117db0fc5.png)
![image](https://user-images.githubusercontent.com/352931/143675535-c2669cd2-71c4-4064-be92-bbc492bf6a97.png)

don't know why =.=

**Comment by Lucifier129** [comment]
It's hard to see what's the problem. We suggest to use `node --inspect ..` to debug the real filename is expected or not.

Note: `cwd` is the path where node.js start at, it's not the `dirname` of current file. Try `http.serve('/static', path.join(__dirname, '..'))` instead. It's better not to serve static directory in root path `/`, it's dangerous and often error-prone.

**Comment by tqma113** [comment]
I get the error. And I find it is caused by the basename matching process bug: `'/'.split('/') === ['', '']`. I will fix it.

**Comment by tqma113** [comment]
https://www.npmjs.com/package/farrow-http/v/1.10.12
