### ISSUE TITLE
Feature request: 提供 ES5 产物

### ISSUE THREAD

**Issue by xuchaobei** [farrow-js/farrow#157]
现在 farrow 下的所有包的产物还是 ES6 语法产物，导致依赖 farrow 包时，出于兼容性考虑，需要将 farrow 相关包进行二次编译为 ES5 语法。

dist/ 路径下直接提供 ES5 产物是不是更合适些呢？

![image](https://user-images.githubusercontent.com/5110783/151530035-11040b4d-8416-4afc-a416-e9a7817ba978.png)

**Comment by Lucifier129** [comment]
@tqma113 帮忙看看是不是 tsconfig.json 的 target 没配好？

**Comment by tqma113** [comment]
"target": "ES6" 可能是这个导致的，我改成 es5
