### ISSUE TITLE
[Discussion] 是否考虑过 farrow-nest？

### ISSUE THREAD

**Issue by yolio2003** [farrow-js/farrow#75]
结合 nest adapter ，替换 express 和 fastify ，是不是可以结合 nest 达到更好的 ts 生态，或者说某些角度上会比较省事儿。
或者说，想明确一个事情，farrow 的目标和愿景是代替 koa 还是说像 nest spring ror 那样更宏大。
如果只是代替 koa ，那么个人觉得做一个 nest-adapter 是不是也不错。

**Comment by Lucifier129** [comment]
## farrow-next

我觉得 `farrow-nest` 可以有，可能更好的形式是作为社区生态。

express 和 fastify 也不是官方提供 nest adapter 适配。

## farrow 目标

farrow 的大致目标层级：

- farrow-http: 用更加类型友好的模式，替代 koa/express
- farrow-api：支持 end-to-end typing，提供工具链，同步后端接口类型到前端
- farrow-*：其他有待探索和发掘的功能

**Comment by yolio2003** [comment]
Sounds great, I look forward to it very much

**Comment by uinz** [comment]
@yolio2003 

我不建议有 farrow-next, 主要理由如下:

1. farrow 和 nest 提升的是开发层的体验, 如 使用 TS类型系统  和 更加友好的开发范式, 但是二者设计理念上应该差异还是比较大的
2. farrow 不像 express, 有很多沉淀的中间件, 足以吸引开发者或者说帮助降低接入门槛
3. farrow 不像 fastify 是以极致性能为目标, 将 farrow 作为 nest 的底层实现没有具体收益

因此我认为并不值得去做

当然以上都是我的个人观点, 欢迎有更多的交流

**Comment by sinoon** [comment]
> @yolio2003
> 
> 我不建议有 farrow-next, 主要理由如下:
> 
> 1. farrow 和 nest 提升的是开发层的体验, 如 使用 TS类型系统  和 更加友好的开发范式, 但是二者设计理念上应该差异还是比较大的
> 2. farrow 不像 express, 有很多沉淀的中间件, 足以吸引开发者或者说帮助降低接入门槛
> 3. farrow 不像 fastify 是以极致性能为目标, 将 farrow 作为 nest 的底层实现没有具体收益
> 
> 因此我认为并不值得去做
> 
> 当然以上都是我的个人观点, 欢迎有更多的交流

赞同你的观点，以实际提供给开发者最优选择的角度以及功利角度上看，我都很认同你的观点。

farrow 和 nest 在提升开发体验的层面上，我觉得提供的支持还是不太一样的，相比起来，nest 输出了一个开发的架构规范与项目组织模式，farrow 并没有在这上面给出任何约束和模式，因此，farrow 我觉得更像是下一个时代的 express/koa 。

也许，未来会有基于 farrow 的 nest.js ，然后再反过来带动 farrow 自身的生态。

**Comment by uinz** [comment]
@sinoon 我认为 Nest.js 核心是基于 class 的 DI 系统, 很大程度借鉴了 Angular

而 farrow 目前来看是基于 Algebraic Effect 的探索, 有不少从 React 借鉴的影子.

Farrow 要达到框架级别的的概念得依靠社区的产出, 这点估计和 React 会有些类似.

Farrow 和 React 一样提供更多的灵活性, 和可玩性并来带一些思考

从这个角度看 Farrow vs Nest 有点类似 React vs Angular

所以我还是想不到 Farrow 和 Nest 如何结合 😁

**Comment by Lucifier129** [comment]
@sinoon @uinz 

对的，鼓励看好 farrow + nest 的开发者们去探索和实践，或许他们看到了其他人没看到的，或许他们在实践过程中，摸索出了新的整合方式也说不定。

社区的产出，来自相信 farrow + * 的开发者们
