### ISSUE TITLE
Feat request: farrow-schema to json-schema

### ISSUE THREAD

**Issue by tqma113** [farrow-js/farrow#90]
How about this? https://github.com/tqma113/farrow-json-schema

**Comment by Lucifier129** [comment]
Good to see it

**Comment by tqma113** [comment]
Which package do I need to add it to in farrow? Or is it to create a new package?

It provides the ability for farrow-schema and farrow-api.

**Comment by Lucifier129** [comment]
`farrow-json-schema` seems already good to use.
