### ISSUE TITLE
CI Problem: npm version 6 vs 7

### ISSUE THREAD

**Issue by tqma113** [farrow-js/farrow#92]
When shift node.js versions from 14(v6.14.13) to 16(npm: 7.11.2), there are two version `package-lock.json` marked by field `lockfileVersion` with `1` and `2`.

That cause `package-lock.json` to change a lot.

So, Which Node.js version（actually npm version） should I use for development and contribution?

FYI: https://github.blog/2021-02-02-npm-7-is-now-generally-available/#breaking-changes

**Comment by Lucifier129** [comment]
Currently, I prefer `node v14`
