### ISSUE TITLE
Feature Request(farrow-client-api): custom fetcher

### ISSUE THREAD

**Issue by tqma113** [farrow-js/farrow#96]

**Comment by Lucifier129** [comment]
Custom fetcher is already supported now.

```typescript
import { apiPipeline } from './someApi'

// assuming this is the last middleware
apiPipeline.use(async (request, next) => {
  // do'nt call next, just perform custom fetching here
  const response = await myFetch(request)
})
```

The internal fetcher is just the last middleware, so it's easy to intercept.

**Comment by tqma113** [comment]
How about this?

```ts
const myApiPipeline = createApiPipeline({ fetcher })
```

Is it valuable？

**Comment by Lucifier129** [comment]
The current usage of `farrow-client-api` is via `codegen`, `createApiPipeline` was called internally, how can a user pass custom fetcher to it?

**Comment by tqma113** [comment]
I used it in `farrow-api-playground`.

And i get a cors error because internal fetcher has set `credentials: 'include'`

![image](https://user-images.githubusercontent.com/22792671/125452121-7915b994-52fc-485c-abd4-c22be26fe0ba.png)

**Comment by Lucifier129** [comment]
I got it!

Maybe adding `apiPipeline.replaceFetcher(newFetcher)` will be good to resolve this problem

**Comment by tqma113** [comment]
I still prefer `const myApiPipeline = createApiPipeline({ fetcher })` because `apiPipeline.replaceFetcher(newFetcher)` will change the fetcher in global and default. In some case, I don't want to do that and just want get a special pipeline.

**Comment by Lucifier129** [comment]
OK, it makes sense.
