### ISSUE TITLE
In the example file `next-app` about `ApiRequest` type errors

### ISSUE THREAD

**Issue by SSShuai1999** [farrow-js/farrow#99]
path: examples/next-app/src/handleApi.ts

![image](https://user-images.githubusercontent.com/28618801/127123941-32ff7090-bec6-4f7f-9bec-5db884d776d9.png)

![image](https://user-images.githubusercontent.com/28618801/127123884-eebd1ca6-388b-4d9e-abda-41d87b123b52.png)

**Comment by tqma113** [comment]
Could we delete this file? It doesn't seem to do anything worthwhile. @Lucifier129

**Comment by Lucifier129** [comment]
@tqma113 These files were for local testing manually. Type errors do not matter.

@SSShuai1999  Shall we just ignore it? It's not the public API and will change frequently while developing

**Comment by SSShuai1999** [comment]
Okay, i see
